pref("extensions.handy_dictionary_ext.autorun", true);
pref("extensions.handy_dictionary_ext.dict", 0);
pref("extensions.handy_dictionary_ext.mode", 0);
pref("extensions.handy_dictionary_ext.failsafe", true);
pref("extensions.handy_dictionary_ext.cl_failsafe", true);
pref("extensions.handy_dictionary_ext.autoclose", 0);
pref("extensions.handy_dictionary_ext.cl_autoclose", 0);
pref("extensions.handy_dictionary_ext.blocklist", "[]");
pref("extensions.handy_dictionary_ext.allowlist", "[]");
pref("extensions.handy_dictionary_ext.key_lookup", ' [["accel"], "M"]');
pref("extensions.handy_dictionary_ext.key_pref", ' [["alt"], "Q"]');
pref("extensions.handy_dictionary_ext.key_about", ' [["alt","accel"], "H"]');
pref("extensions.handy_dictionary_ext.key_toggle", ' [["alt"], "O"]');
