pref("extensions.handy_dictionary_ext.autorun", true);
pref("extensions.handy_dictionary_ext.dict", 0);
pref("extensions.handy_dictionary_ext.mode", 0);
pref("extensions.handy_dictionary_ext.failsafe", true);
pref("extensions.handy_dictionary_ext.cl_failsafe", true);
pref("extensions.handy_dictionary_ext.autoclose", 0);
pref("extensions.handy_dictionary_ext.cl_autoclose", 0);
pref("extensions.handy_dictionary_ext.blocklist", "[]");
pref("extensions.handy_dictionary_ext.allowlist", "[]");
